# Generated by Django 5.0.7 on 2024-07-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
